// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyCphrFbj-DCB_gZ7ljaEZEtZv1Whp2tU',
    appId: '1:974617715967:web:95e07e654f14f4c6f798ca',
    messagingSenderId: '974617715967',
    projectId: 'locally-ceb80',
    authDomain: 'locally-ceb80.firebaseapp.com',
    storageBucket: 'locally-ceb80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNPmk1cpmkddEovxGAKrSFPQAwC6spTwE',
    appId: '1:974617715967:android:5bc9491c15476728f798ca',
    messagingSenderId: '974617715967',
    projectId: 'locally-ceb80',
    storageBucket: 'locally-ceb80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYclqkCEhemY91Xw4jsXFW5FCNZ31hJf8',
    appId: '1:974617715967:ios:c9de0b0478e9803ff798ca',
    messagingSenderId: '974617715967',
    projectId: 'locally-ceb80',
    storageBucket: 'locally-ceb80.firebasestorage.app',
    iosBundleId: 'com.example.locally',
  );
}
