import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:locally/common/models/chat/chat_models.dart';

final chatServiceProvider = Provider((ref) {
  return ChatService(Supabase.instance.client);
});

final unreadChatCountProvider = StreamProvider.family<int, String>((ref, myId) {
  return ref.watch(chatServiceProvider)
      .getMyChatRoomsStream(myId)
      .map((rooms) {
        int total = 0;
        for (var room in rooms) {
          // Uses the helper method we defined in your ChatRoom model
          total += room.getMyUnreadCount(myId);
        }
        return total;
      });
});

class ChatService {
  final SupabaseClient _client;
  ChatService(this._client);

  // 1. Create or Get existing Room
  Future<String> createOrGetChatRoom(String myId, String otherId) async {
    // Check if room exists (1-2 or 2-1)
    final response = await _client
        .from('chat_rooms')
        .select()
        .or('and(participant_1.eq.$myId,participant_2.eq.$otherId),and(participant_1.eq.$otherId,participant_2.eq.$myId)');

    if (response.isNotEmpty) {
      return response.first['id'] as String;
    }

    // Create new room
    final newRoom = await _client.from('chat_rooms').insert({
      'participant_1': myId,
      'participant_2': otherId,
      'last_message_time': DateTime.now().toIso8601String(),
      'unread_count_p1': 0,
      'unread_count_p2': 0,
    }).select();

    return newRoom.first['id'] as String;
  }

  // 2. Stream My Chat Rooms
  Stream<List<ChatRoom>> getMyChatRoomsStream(String myId) {
    return _client
        .from('chat_rooms')
        .stream(primaryKey: ['id'])
        .order('last_message_time', ascending: false)
        .map((data) {
          // Filter locally to ensure we only see our rooms
          final myRooms = data.where((room) =>
              room['participant_1'] == myId ||
              room['participant_2'] == myId
          ).toList();
          
          return myRooms.map((e) => ChatRoom.fromMap(e)).toList();
        });
  }

  // 3. Stream Messages for a Room
  Stream<List<ChatMessage>> getMessagesStream(String roomId) {
    return _client
        .from('messages')
        .stream(primaryKey: ['id'])
        .eq('room_id', roomId)
        .order('created_at', ascending: true) // Stream expects strict ordering
        .map((data) => data.map((e) => ChatMessage.fromMap(e)).toList());
  }

  // 4. Send Message
  Future<void> sendMessage(String roomId, String senderId, String content) async {
    await _client.from('messages').insert({
      'room_id': roomId,
      'sender_id': senderId,
      'content': content,
      // created_at is auto-generated by DB
    });
    // Note: Your DB Trigger should handle updating 'last_message' and incrementing 'unread_count'
  }

  // 5. Mark Room as Read
  // This was missing in your original code but called in ChatScreen
  Future<void> markRoomAsRead(String roomId, String myId) async {
    // We need to know if we are participant 1 or 2 to reset the correct counter.
    // We can fetch the room once to check.
    final roomData = await _client
        .from('chat_rooms')
        .select('participant_1, participant_2')
        .eq('id', roomId)
        .maybeSingle();

    if (roomData == null) return;

    final p1 = roomData['participant_1'];

    if (myId == p1) {
      await _client
          .from('chat_rooms')
          .update({'unread_count_p1': 0})
          .eq('id', roomId);
    } else {
      await _client
          .from('chat_rooms')
          .update({'unread_count_p2': 0})
          .eq('id', roomId);
    }
  }
}